### ISSUE TITLE
An issue with arguments

### ISSUE THREAD

**Issue by annwhoorma** [annwhoorma/DS20-project-2#4]
https://github.com/annwhoorma/DS20-project-2/blob/eb981bb82c527c45d4246012e42ad56d0a84342b/server.py#L248

the referenced function ( accepts ```message``` from ```do_GET``` but ```do_GET``` passes the whole json
then, there is ```process = Process(target=receive_file(message))```. i just don't get, do we pass the whole json thing to ```Process```? aren't we supposed to pass only the content of the file?
```message```:
```json
{
    "command": "write_file",
    "args": {
        "user": "/anya",
        "path": "/folder1/folder2/file",
        "message": "msg"
    }
}
```

and the content of the file is stored in ```message['args']['message']```

**Comment by screemix** [comment]
![telegram-cloud-photo-size-2-5474414768191287651-x](https://user-images.githubusercontent.com/43718473/95455523-af7e1a00-0976-11eb-9b7f-0d5f7b978160.jpg)
у меня есть функцсия райт файл, которая создает процесс, чтобы сервер мог принимать команды, стучать сердечками и тп вне зависимости от того, сколько там еще писать файл осталось
процесс сам по себе есть функция ресив файл, которая открывает порт и слушает  и качает с порта файл, записывая его. как файл закончится, процесс схлопнется
